# Site settings
title: Full Stack Learner
header-img: img/home-bg.jpg
email: abreu.wilbert@gmail.com
description: "TBD"
baseurl: ""
url: "http://fullstacklearner.com"
twitter_username: wilbert_abreu
github_username:  wilbert-abreu
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
